#ifndef SCHEDULEMASTER_GLOBAL_H
#define SCHEDULEMASTER_GLOBAL_H

#include <QtCore/QtGlobal>

// test
#define SCHEDULEMASTER_API

#if defined(SCHEDULEMASTER_API)
#define SCHEDULEMASTERINTERFACE_EXPORT Q_DECL_EXPORT
#else
#define SCHEDULEMASTERINTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // SCHEDULEMASTER_GLOBAL_H
