#ifndef SCHEDULEMASTERINTERFACE_GLOBAL_H
#define SCHEDULEMASTERINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCHEDULEMASTERINTERFACE_LIBRARY)
#define SCHEDULEMASTERINTERFACE_EXPORT Q_DECL_EXPORT
#else
#define SCHEDULEMASTERINTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // SCHEDULEMASTERINTERFACE_GLOBAL_H
